# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

networks:
  default:
    external:
      name: backend